config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users do
    post 'toggle_account_access', on: :member
  end

  resources :beers
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'brewerylist', to: 'breweries#list'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resource :session, only: [:new, :create, :delete]
  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true, length: { minimum: 3, maximum: 15 }
  validates :password, length: { minimum: 4 }
  validates :password, format: { with: /(?=.*\d)(?=.*[A-Z])/, message: "must contain at least one capital letter and one number!"}

  has_many :ratings
  has_many :beers, through: :ratings
  has_many :memberships
  has_many :beer_clubs, through: :memberships

  def self.top(n)
    sorted_by_number_of_ratings_desc = User.all.sort_by{ |u| -(u.ratings.count) }
    top_n = sorted_by_number_of_ratings_desc[0..(n-1)]
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?
    beers_and_ratings_joined = Style.joins(:ratings).where("ratings.user_id = #{id}")
    styles_with_scores = beers_and_ratings_joined.select("styles.name as style, avg(score) as total_score").group("style")
    styles_with_scores.sort_by{|style| style.total_score}.last.style
  end

  def favorite_brewery
    return nil if ratings.empty?
    breweries_and_ratings_joined = Brewery.joins(:ratings).where("ratings.user_id = #{id}")
    breweries_and_scores = breweries_and_ratings_joined.select("breweries.name, avg(score) as total_score").group("breweries.name")
    breweries_and_scores.sort_by{|brewery| brewery.total_score}.last.name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def toggle_account_access
    user = User.find(params[:id])
    user.update_attribute :access, (not user.access)

    new_status = user.access? ? "active" : "frozen"

    redirect_to :back, notice: "Account status changed to #{new_status}"
  end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params) && @user == current_user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.ratings.each{|rating| rating.delete}
      @user.memberships.each{|membership| membership.delete}
      @user.destroy
      session.destroy
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> Rated beers </th>
      <th> Total ratings </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if !user.access and current_user and current_user.admin %>
                <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.username %>
  <% if not @user.access %>
      <span class="label label-info">account frozen</span>
  <% end %>
</h2>

<p>
  Has made <%= @user.ratings.count %> ratings
</p>

<% if !@user.access and current_user and current_user.admin %>
    <%= link_to 'Reactivate account', toggle_account_access_user_path(@user.id), method: :post, class: 'btn btn-primary' %>
<% elsif @user.access and current_user and current_user.admin %>
    <%= link_to 'Froze account', toggle_account_access_user_path(@user.id), method: :post, class: 'btn btn-primary' %>
<% end %>

<h3>Ratings</h3>

<ul>
  <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %>
        <% if @user == current_user %>
            <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </li>
  <% end %>
</ul>

<p>
  Average of ratings: <%= round(@user.average_rating) %>
</p>

<p>
  <% if @user.ratings.empty? %>
      Doesn't have a favorite beer yet!
  <% else %>
      Favorite beer is <%= @user.favorite_beer %>
  <% end %>
</p>

<p>
  <% if @user.ratings.empty? %>
    Doesn't have a favorite style yet!
  <% else %>
    Favorite style is <%= @user.favorite_style %>
  <% end %>
</p>

<p>
  <% if @user.ratings.empty? %>
    Doesn't have a favorite brewery yet!
  <% else %>
    Favorite brewery is <%= @user.favorite_brewery %>
  <% end %>
</p>

<p>
  <% if @user.memberships.empty? %>
  Not a member of any beer club
  <% else %>
  Member of <% @user.memberships.each do |membership| %>
          <%= link_to membership.beer_club.name, membership.beer_club %>
      <% end %>
  <% end %>
</p>

<% if @user == current_user %>
    <td><%= link_to 'Edit', edit_user_path(@user), class:'btn btn-success' %></td>
    <td><%= link_to 'Destroy', @user, class:'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>