config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users do
    post 'toggle_account_access', on: :member
  end

  resources :beers
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'brewerylist', to: 'breweries#list'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resource :session, only: [:new, :create, :delete]
  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1042, only_integer: true}
  validate :brewery_cannot_be_established_in_the_future

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil, false] }

  def brewery_cannot_be_established_in_the_future
    if self.year > Date.today.year
      errors.add(:year, "can't be after #{Date.today.year}!")
    end
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
    top_n = sorted_by_rating_in_desc_order[0..(n-1)]
  end

  def print_report
    puts self.name
    puts "established at year #{self.year}"
    puts "number of beers #{self.beers.count}"
  end

  def restart
    self.year = 2015
    puts "changed year to #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_user_is_admin, only: :destroy
  before_action :skip_if_cached, only: :index
  # GET /breweries
  # GET /breweries.json
  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerieslist-#{@order}")
  end

  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    @active_breweries = case @order
                          when 'name' then @active_breweries.sort_by{|b| b.name}
                          when 'year' then @active_breweries.sort_by{|b| b.year}
                        end

    @retired_breweries = case @order
                           when 'name' then @retired_breweries.sort_by{|b| b.name}
                           when 'year' then @retired_breweries.sort_by { |b| b.year}
                         end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  def list
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ["brewerieslist-name", "brewerieslist-year"].each{|b| expire_fragment(b)}
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["brewerieslist-active-name", "brewerieslist-active-year", "brewerieslist-retired-name", "breweries-retired-year"].each{|b| expire_fragment(b)}
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["brewerieslist-active-name", "brewerieslist-active-year", "brewerieslist-retired-name", "breweries-retired-year"].each{|b| expire_fragment(b)}
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
    <div class="field">
      <%= f.label :active %><br>
      <%= f.check_box :active %>
    </div>
  <div class="actions">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></a></td>
        <td><%= brewery.year %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries</h1>

<div style="border-style: solid;">
  brewerieslist-name: <%= ActionController::Base.new.fragment_exist?( 'brewerieslist-name') %>
  <br />
  brewerieslist-year: <%= ActionController::Base.new.fragment_exist?( 'brewerieslist-year') %>
</div>

<% cache "brewerieslist-#{@order}", skip_digest: true do %>

<h2>Active</h2>

<p>Number of active breweries: <%= @active_breweries.count%></p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p>Number of retired breweries <%= @retired_breweries.count %></p>

<%= render 'list', breweries: @retired_breweries %>

<% end %>

<br>

<%= link_to 'Create a brewery', new_brewery_path, class:'btn btn-success' if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <thead>
  <th> <a href="#" id="breweryname">Name</a> </th>
  <th> <a href="#" id="year">Established in</a> </th>
  <th> <a href="#" id="count">Number of beers</a> </th>
  </thead>
</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @brewery do %>

<h2>
  <%= @brewery.name %>
  <% if not @brewery.active %>
    <span class="label label-info">retired</span>
  <% end %>
</h2>

<p>
  <i>Established in <%= @brewery.year %></i>
</p>

<p>
  Number of beers: <%= @brewery.beers.count %>
</p>

<ul>
  <% @brewery.beers.each do |beer| %>
  <li><%= link_to beer.name, beer %></li>
  <% end %>
</ul>

<p>
  <% if @brewery.ratings.empty? %>
      No ratings have been given yet!
  <% else %>
  Has <%= @brewery.ratings.count%> <%= "rating".pluralize(@brewery.ratings.count) %>, average <%= round(@brewery.average_rating) %>
  <% end %>
</p>

    <% end %>

    <% if current_user %>

<%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<br />
<%= edit_and_destroy_buttons(@brewery) %>

<% end %>