config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users do
    post 'toggle_account_access', on: :member
  end

  resources :beers
  get 'kaikki_bisset', to: 'beers#index'
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'brewerylist', to: 'breweries#list'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resource :session, only: [:new, :create, :delete]
  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Breweries', breweries_path, class:'btn' %></li>
<li><%= link_to 'Beers', beers_path, class:'btn' %></li>
<li><%= link_to 'Styles', styles_path, class:'btn' %></li>
<li><%= link_to 'Ratings', ratings_path, class:'btn' %></li>
<li><%= link_to 'Users', users_path, class:'btn' %></li>
<li><%= link_to 'Clubs', beer_clubs_path, class:'btn' %></li>
<li><%= link_to 'Places', places_path, class:'btn' %></li>

<% if not session[:user_id].nil? %>
    <li>
        <a href="#" class="btn dropdown-toggle" data-toggle="dropdown" aria-
            expanded="false"><%= current_user.username %> <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'My page', current_user %></li>
            <li><%= link_to 'Rate a beer', new_rating_path %></li>
            <li><%= link_to 'Join a club', new_membership_path %></li>
            <li><%= link_to 'Sign out', signout_path, method: :delete %></li>
        </ul>
    </li>
<% else %>
    <li><%= link_to 'Sign in', signin_path %></li>
    <li><%= link_to 'Sign up', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ratebeer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ratebeer" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class=".container">
       <%= render 'layouts/messages' %>

      <div class="row">
        <div class="col-md-8">
            <%= yield %>
        </div>
        <div class="col-md-4">
            <img src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg" width="200">
        </div>
      </div>
    </main>
  </body>
</html>